### ISSUE TITLE
open /usr/src/cmd/cgo: no such file or directory

### ISSUE THREAD

**Issue by medined** [emicklei/rango#3]
I tried to find information on this issue using a web search but failed. I'm hoping you can help even if the issue is not directly associated with rango. Here is the error:

```
$ go get -v github.com/emicklei/rango
github.com/emicklei/rango (download)
github.com/GeertJohan/go.linenoise (download)
load cmd/cgo: package cmd/cgo: open /usr/src/cmd/cgo: no such file or directory
```

**Comment by emicklei** [comment]
not seen that one before.  Did you set the GOPATH variable to an absolute path?

GOPATH is where you want to store your go code, not where you installed the go compiler.  
     export GOPATH=$HOME
